library(shinydashboard)
library(shiny)
library(tidyverse)
library(shinyFiles)
library(devtools)
require (Rfacebook)
library(tm)
library(wordcloud)
library(stylo)
library(tidytext)
library(xlsx)
library(gdata)
library(readxl)
library(lubridate)
library(htmlwidgets)
